"""A typed Morpholog client for programme `grid_mysteries_research_v2`.

GENERATED by `morpholog generate python-client` - do not edit;
regenerate when the programme changes. The model hash in
`__init__.py` names the rules this client was built against.
"""

import sys

if sys.version_info < (3, 10):
    raise RuntimeError(
        f"morpholog_client requires Python 3.10+ "
        f"(running {sys.version_info.major}.{sys.version_info.minor}); "
        f"the generated code holds a conservative floor on purpose"
    )

PROGRAM = "grid_mysteries_research_v2"
MODEL_HASH = "sha256:c9e4b9371e3db420726d501424b8ca1f0766535fe9f549da5fe843e302dbbda2"
MORPHOLOG_VERSION = "0.0.9"
PYTHON_FLOOR = (3, 10)

from . import envelopes, models, values  # noqa: E402
from .adapter import Morpholog, MorphologError  # noqa: E402
from .session import (  # noqa: E402
    MorphologOutcomeUnknown,
    MorphologRequestError,
    Session,
)

def open_session(
    file: str,
    database_url: str,
    *,
    binary: str | None = None,
    timeout: float | None = None,
) -> Session:
    """Open a session pinned to the programme this package was
    generated from: a binary serving any other rules is refused at
    the handshake, before a single proposal is written. Construct
    ``Session`` directly to open deliberately unpinned."""
    return Session(
        file,
        database_url,
        binary=binary,
        timeout=timeout,
        expected_model_hash=MODEL_HASH,
    )


__all__ = [
    "PROGRAM",
    "MODEL_HASH",
    "MORPHOLOG_VERSION",
    "PYTHON_FLOOR",
    "Morpholog",
    "MorphologError",
    "MorphologOutcomeUnknown",
    "MorphologRequestError",
    "Session",
    "open_session",
    "envelopes",
    "models",
    "values",
]
