"""Typed request, read, and payload models for programme `grid_mysteries_research_v2`.

GENERATED by `morpholog generate python-client` - do not edit;
regenerate when the programme changes. The model hash in
`__init__.py` names the rules this client was built against.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import ClassVar

from . import values


@dataclass(frozen=True)
class EstablishGovernanceRequest:
    """Arguments for `establish_governance`."""

    TRANSFORMATION: ClassVar[str] = "establish_governance"

    human_actor: str
    human_login_role: str
    machine_actor: str
    machine_login_role: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "human_actor": values.encode_named(self.human_actor),
            "human_login_role": values.encode_named(self.human_login_role),
            "machine_actor": values.encode_named(self.machine_actor),
            "machine_login_role": values.encode_named(self.machine_login_role),
        }


@dataclass(frozen=True)
class RegisterAuditSigningKeyRequest:
    """Arguments for `register_audit_signing_key`."""

    TRANSFORMATION: ClassVar[str] = "register_audit_signing_key"

    key_id: str
    public_key: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "key_id": values.encode_named(self.key_id),
            "public_key": values.encode_named(self.public_key),
        }


@dataclass(frozen=True)
class OpenInquiryRequest:
    """Arguments for `open_inquiry`."""

    TRANSFORMATION: ClassVar[str] = "open_inquiry"

    inquiry: str
    kind: str
    title: str
    opened_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "kind": values.encode_named(self.kind),
            "title": values.encode_named(self.title),
            "opened_at": values.encode_named(self.opened_at),
        }


@dataclass(frozen=True)
class RegisterCorpusRequest:
    """Arguments for `register_corpus`."""

    TRANSFORMATION: ClassVar[str] = "register_corpus"

    corpus: str
    first_day: date
    last_day: date

    def to_args_named(self) -> dict[str, object]:
        return {
            "corpus": values.encode_named(self.corpus),
            "first_day": values.encode_named(self.first_day),
            "last_day": values.encode_named(self.last_day),
        }


@dataclass(frozen=True)
class AssignCorpusRequest:
    """Arguments for `assign_corpus`."""

    TRANSFORMATION: ClassVar[str] = "assign_corpus"

    inquiry: str
    corpus: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "corpus": values.encode_named(self.corpus),
        }


@dataclass(frozen=True)
class ConsumeCorpusRequest:
    """Arguments for `consume_corpus`."""

    TRANSFORMATION: ClassVar[str] = "consume_corpus"

    corpus: str
    inquiry: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "corpus": values.encode_named(self.corpus),
            "inquiry": values.encode_named(self.inquiry),
        }


@dataclass(frozen=True)
class RecordHistoricalConsumptionRequest:
    """Arguments for `record_historical_consumption`."""

    TRANSFORMATION: ClassVar[str] = "record_historical_consumption"

    corpus: str
    v1_consumer: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "corpus": values.encode_named(self.corpus),
            "v1_consumer": values.encode_named(self.v1_consumer),
        }


@dataclass(frozen=True)
class DeclareParameterRequest:
    """Arguments for `declare_parameter`."""

    TRANSFORMATION: ClassVar[str] = "declare_parameter"

    inquiry: str
    name: str
    parameter_value: Decimal

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "name": values.encode_named(self.name),
            "parameter_value": values.encode_named(self.parameter_value),
        }


@dataclass(frozen=True)
class DeclareProtocolRequest:
    """Arguments for `declare_protocol`."""

    TRANSFORMATION: ClassVar[str] = "declare_protocol"

    inquiry: str
    protocol_digest: str
    declared_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "protocol_digest": values.encode_named(self.protocol_digest),
            "declared_at": values.encode_named(self.declared_at),
        }


@dataclass(frozen=True)
class SealProtocolRequest:
    """Arguments for `seal_protocol`."""

    TRANSFORMATION: ClassVar[str] = "seal_protocol"

    inquiry: str
    sealed_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "sealed_at": values.encode_named(self.sealed_at),
        }


@dataclass(frozen=True)
class RegisterEvidenceRequest:
    """Arguments for `register_evidence`."""

    TRANSFORMATION: ClassVar[str] = "register_evidence"

    artifact: str
    source: str
    sha256: str
    fetched_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "artifact": values.encode_named(self.artifact),
            "source": values.encode_named(self.source),
            "sha256": values.encode_named(self.sha256),
            "fetched_at": values.encode_named(self.fetched_at),
        }


@dataclass(frozen=True)
class AttachEvidenceRequest:
    """Arguments for `attach_evidence`."""

    TRANSFORMATION: ClassVar[str] = "attach_evidence"

    inquiry: str
    artifact: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "artifact": values.encode_named(self.artifact),
        }


@dataclass(frozen=True)
class SealEvidenceRequest:
    """Arguments for `seal_evidence`."""

    TRANSFORMATION: ClassVar[str] = "seal_evidence"

    inquiry: str
    sealed_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "sealed_at": values.encode_named(self.sealed_at),
        }


@dataclass(frozen=True)
class RecordSelectionRequest:
    """Arguments for `record_selection`."""

    TRANSFORMATION: ClassVar[str] = "record_selection"

    inquiry: str
    selection_digest: str
    recorded_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "selection_digest": values.encode_named(self.selection_digest),
            "recorded_at": values.encode_named(self.recorded_at),
        }


@dataclass(frozen=True)
class RegisterConjectureRequest:
    """Arguments for `register_conjecture`."""

    TRANSFORMATION: ClassVar[str] = "register_conjecture"

    conjecture: str
    inquiry: str
    statement: str
    proposed_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "conjecture": values.encode_named(self.conjecture),
            "inquiry": values.encode_named(self.inquiry),
            "statement": values.encode_named(self.statement),
            "proposed_at": values.encode_named(self.proposed_at),
        }


@dataclass(frozen=True)
class AssessMechanismRequest:
    """Arguments for `assess_mechanism`."""

    TRANSFORMATION: ClassVar[str] = "assess_mechanism"

    inquiry: str
    mechanism: str
    status: str
    evidence_digest: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "mechanism": values.encode_named(self.mechanism),
            "status": values.encode_named(self.status),
            "evidence_digest": values.encode_named(self.evidence_digest),
        }


@dataclass(frozen=True)
class BindMetricRequest:
    """Arguments for `bind_metric`."""

    TRANSFORMATION: ClassVar[str] = "bind_metric"

    metric: str
    inquiry: str
    artifact: str
    metric_name: str
    metric_value: Decimal

    def to_args_named(self) -> dict[str, object]:
        return {
            "metric": values.encode_named(self.metric),
            "inquiry": values.encode_named(self.inquiry),
            "artifact": values.encode_named(self.artifact),
            "metric_name": values.encode_named(self.metric_name),
            "metric_value": values.encode_named(self.metric_value),
        }


@dataclass(frozen=True)
class DeclareRetentionRequest:
    """Arguments for `declare_retention`."""

    TRANSFORMATION: ClassVar[str] = "declare_retention"

    inquiry: str
    surviving_name: str
    baseline_name: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "surviving_name": values.encode_named(self.surviving_name),
            "baseline_name": values.encode_named(self.baseline_name),
        }


@dataclass(frozen=True)
class LinkMetricRequest:
    """Arguments for `link_metric`."""

    TRANSFORMATION: ClassVar[str] = "link_metric"

    conclusion: str
    metric: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "conclusion": values.encode_named(self.conclusion),
            "metric": values.encode_named(self.metric),
        }


@dataclass(frozen=True)
class PublishConclusionRequest:
    """Arguments for `publish_conclusion`."""

    TRANSFORMATION: ClassVar[str] = "publish_conclusion"

    conclusion: str
    inquiry: str
    conjecture: str
    conclusion_class: str
    statement: str
    evidence_digest: str
    published_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "conclusion": values.encode_named(self.conclusion),
            "inquiry": values.encode_named(self.inquiry),
            "conjecture": values.encode_named(self.conjecture),
            "conclusion_class": values.encode_named(self.conclusion_class),
            "statement": values.encode_named(self.statement),
            "evidence_digest": values.encode_named(self.evidence_digest),
            "published_at": values.encode_named(self.published_at),
        }


@dataclass(frozen=True)
class SupersedeConclusionRequest:
    """Arguments for `supersede_conclusion`."""

    TRANSFORMATION: ClassVar[str] = "supersede_conclusion"

    successor: str
    prior: str
    inquiry: str
    conjecture: str
    conclusion_class: str
    statement: str
    evidence_digest: str
    published_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "successor": values.encode_named(self.successor),
            "prior": values.encode_named(self.prior),
            "inquiry": values.encode_named(self.inquiry),
            "conjecture": values.encode_named(self.conjecture),
            "conclusion_class": values.encode_named(self.conclusion_class),
            "statement": values.encode_named(self.statement),
            "evidence_digest": values.encode_named(self.evidence_digest),
            "published_at": values.encode_named(self.published_at),
        }


@dataclass(frozen=True)
class DraftPublicationRequest:
    """Arguments for `draft_publication`."""

    TRANSFORMATION: ClassVar[str] = "draft_publication"

    publication: str
    conclusion: str
    medium: str
    content_digest: str
    drafted_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "publication": values.encode_named(self.publication),
            "conclusion": values.encode_named(self.conclusion),
            "medium": values.encode_named(self.medium),
            "content_digest": values.encode_named(self.content_digest),
            "drafted_at": values.encode_named(self.drafted_at),
        }


@dataclass(frozen=True)
class ApprovePublicationRequest:
    """Arguments for `approve_publication`."""

    TRANSFORMATION: ClassVar[str] = "approve_publication"

    publication: str
    approved_at: datetime

    def to_args_named(self) -> dict[str, object]:
        return {
            "publication": values.encode_named(self.publication),
            "approved_at": values.encode_named(self.approved_at),
        }


@dataclass(frozen=True)
class RecordV1LineageRequest:
    """Arguments for `record_v1_lineage`."""

    TRANSFORMATION: ClassVar[str] = "record_v1_lineage"

    inquiry: str
    v1_investigation: str

    def to_args_named(self) -> dict[str, object]:
        return {
            "inquiry": values.encode_named(self.inquiry),
            "v1_investigation": values.encode_named(self.v1_investigation),
        }


@dataclass(frozen=True)
class ActorAssertionRestrictedClaim:
    """One admitted `ActorAssertionRestricted` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "ActorAssertionRestricted"

    actor: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> ActorAssertionRestrictedClaim:
        raw = args["actor"]
        actor = raw
        return cls(actor=actor)


@dataclass(frozen=True)
class ActorAssertionAuthorityClaim:
    """One admitted `ActorAssertionAuthority` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "ActorAssertionAuthority"

    actor: str
    login_role: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> ActorAssertionAuthorityClaim:
        raw = args["actor"]
        actor = raw
        raw = args["login_role"]
        login_role = raw
        return cls(actor=actor, login_role=login_role)


@dataclass(frozen=True)
class SealAuthorityClaim:
    """One admitted `SealAuthority` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "SealAuthority"

    actor: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> SealAuthorityClaim:
        raw = args["actor"]
        actor = raw
        return cls(actor=actor)


@dataclass(frozen=True)
class PublicationAuthorityClaim:
    """One admitted `PublicationAuthority` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "PublicationAuthority"

    actor: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> PublicationAuthorityClaim:
        raw = args["actor"]
        actor = raw
        return cls(actor=actor)


@dataclass(frozen=True)
class AuditSigningKeyClaim:
    """One admitted `AuditSigningKey` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "AuditSigningKey"

    key_id: str
    purpose: str
    public_key: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> AuditSigningKeyClaim:
        raw = args["key_id"]
        key_id = raw
        raw = args["purpose"]
        purpose = raw
        raw = args["public_key"]
        public_key = raw
        return cls(key_id=key_id, purpose=purpose, public_key=public_key)


@dataclass(frozen=True)
class InquiryClaim:
    """One admitted `Inquiry` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "Inquiry"

    inquiry: str
    kind: str
    title: str
    opened_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> InquiryClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["kind"]
        kind = raw
        raw = args["title"]
        title = raw
        raw = args["opened_at"]
        opened_at = values.parse_timestamp(raw)
        return cls(inquiry=inquiry, kind=kind, title=title, opened_at=opened_at)


@dataclass(frozen=True)
class ResearchCorpusClaim:
    """One admitted `ResearchCorpus` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "ResearchCorpus"

    corpus: str
    first_day: date
    last_day: date

    @classmethod
    def from_named(cls, args: dict[str, object]) -> ResearchCorpusClaim:
        raw = args["corpus"]
        corpus = raw
        raw = args["first_day"]
        first_day = values.parse_date(raw)
        raw = args["last_day"]
        last_day = values.parse_date(raw)
        return cls(corpus=corpus, first_day=first_day, last_day=last_day)


@dataclass(frozen=True)
class InquiryCorpusClaim:
    """One admitted `InquiryCorpus` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "InquiryCorpus"

    inquiry: str
    corpus: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> InquiryCorpusClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["corpus"]
        corpus = raw
        return cls(inquiry=inquiry, corpus=corpus)


@dataclass(frozen=True)
class CorpusConsumedClaim:
    """One admitted `CorpusConsumed` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "CorpusConsumed"

    corpus: str
    consumer: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> CorpusConsumedClaim:
        raw = args["corpus"]
        corpus = raw
        raw = args["consumer"]
        consumer = raw
        return cls(corpus=corpus, consumer=consumer)


@dataclass(frozen=True)
class ProtocolDeclaredClaim:
    """One admitted `ProtocolDeclared` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "ProtocolDeclared"

    inquiry: str
    protocol_digest: str
    declared_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> ProtocolDeclaredClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["protocol_digest"]
        protocol_digest = raw
        raw = args["declared_at"]
        declared_at = values.parse_timestamp(raw)
        return cls(inquiry=inquiry, protocol_digest=protocol_digest, declared_at=declared_at)


@dataclass(frozen=True)
class ProtocolSealedClaim:
    """One admitted `ProtocolSealed` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "ProtocolSealed"

    inquiry: str
    sealed_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> ProtocolSealedClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["sealed_at"]
        sealed_at = values.parse_timestamp(raw)
        return cls(inquiry=inquiry, sealed_at=sealed_at)


@dataclass(frozen=True)
class DeclaredParameterClaim:
    """One admitted `DeclaredParameter` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "DeclaredParameter"

    inquiry: str
    name: str
    parameter_value: Decimal

    @classmethod
    def from_named(cls, args: dict[str, object]) -> DeclaredParameterClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["name"]
        name = raw
        raw = args["parameter_value"]
        parameter_value = values.parse_decimal(raw)
        return cls(inquiry=inquiry, name=name, parameter_value=parameter_value)


@dataclass(frozen=True)
class EvidenceArtifactClaim:
    """One admitted `EvidenceArtifact` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "EvidenceArtifact"

    artifact: str
    source: str
    sha256: str
    fetched_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> EvidenceArtifactClaim:
        raw = args["artifact"]
        artifact = raw
        raw = args["source"]
        source = raw
        raw = args["sha256"]
        sha256 = raw
        raw = args["fetched_at"]
        fetched_at = values.parse_timestamp(raw)
        return cls(artifact=artifact, source=source, sha256=sha256, fetched_at=fetched_at)


@dataclass(frozen=True)
class InquiryUsesClaim:
    """One admitted `InquiryUses` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "InquiryUses"

    inquiry: str
    artifact: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> InquiryUsesClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["artifact"]
        artifact = raw
        return cls(inquiry=inquiry, artifact=artifact)


@dataclass(frozen=True)
class EvidenceSealedClaim:
    """One admitted `EvidenceSealed` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "EvidenceSealed"

    inquiry: str
    sealed_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> EvidenceSealedClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["sealed_at"]
        sealed_at = values.parse_timestamp(raw)
        return cls(inquiry=inquiry, sealed_at=sealed_at)


@dataclass(frozen=True)
class SelectionRecordedClaim:
    """One admitted `SelectionRecorded` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "SelectionRecorded"

    inquiry: str
    selection_digest: str
    recorded_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> SelectionRecordedClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["selection_digest"]
        selection_digest = raw
        raw = args["recorded_at"]
        recorded_at = values.parse_timestamp(raw)
        return cls(inquiry=inquiry, selection_digest=selection_digest, recorded_at=recorded_at)


@dataclass(frozen=True)
class ConjectureClaim:
    """One admitted `Conjecture` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "Conjecture"

    conjecture: str
    inquiry: str
    statement: str
    proposed_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> ConjectureClaim:
        raw = args["conjecture"]
        conjecture = raw
        raw = args["inquiry"]
        inquiry = raw
        raw = args["statement"]
        statement = raw
        raw = args["proposed_at"]
        proposed_at = values.parse_timestamp(raw)
        return cls(conjecture=conjecture, inquiry=inquiry, statement=statement, proposed_at=proposed_at)


@dataclass(frozen=True)
class MechanismAssessmentClaim:
    """One admitted `MechanismAssessment` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "MechanismAssessment"

    inquiry: str
    mechanism: str
    status: str
    evidence_digest: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> MechanismAssessmentClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["mechanism"]
        mechanism = raw
        raw = args["status"]
        status = raw
        raw = args["evidence_digest"]
        evidence_digest = raw
        return cls(inquiry=inquiry, mechanism=mechanism, status=status, evidence_digest=evidence_digest)


@dataclass(frozen=True)
class EvidenceMetricClaim:
    """One admitted `EvidenceMetric` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "EvidenceMetric"

    metric: str
    inquiry: str
    artifact: str
    metric_name: str
    metric_value: Decimal

    @classmethod
    def from_named(cls, args: dict[str, object]) -> EvidenceMetricClaim:
        raw = args["metric"]
        metric = raw
        raw = args["inquiry"]
        inquiry = raw
        raw = args["artifact"]
        artifact = raw
        raw = args["metric_name"]
        metric_name = raw
        raw = args["metric_value"]
        metric_value = values.parse_decimal(raw)
        return cls(metric=metric, inquiry=inquiry, artifact=artifact, metric_name=metric_name, metric_value=metric_value)


@dataclass(frozen=True)
class ConclusionUsesMetricClaim:
    """One admitted `ConclusionUsesMetric` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "ConclusionUsesMetric"

    conclusion: str
    metric: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> ConclusionUsesMetricClaim:
        raw = args["conclusion"]
        conclusion = raw
        raw = args["metric"]
        metric = raw
        return cls(conclusion=conclusion, metric=metric)


@dataclass(frozen=True)
class RetentionSpecClaim:
    """One admitted `RetentionSpec` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "RetentionSpec"

    inquiry: str
    surviving_name: str
    baseline_name: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> RetentionSpecClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["surviving_name"]
        surviving_name = raw
        raw = args["baseline_name"]
        baseline_name = raw
        return cls(inquiry=inquiry, surviving_name=surviving_name, baseline_name=baseline_name)


@dataclass(frozen=True)
class MetricRetentionClaim:
    """One admitted `MetricRetention` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "MetricRetention"

    inquiry: str
    surviving_name: str
    baseline_name: str
    ratio: Decimal

    @classmethod
    def from_named(cls, args: dict[str, object]) -> MetricRetentionClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["surviving_name"]
        surviving_name = raw
        raw = args["baseline_name"]
        baseline_name = raw
        raw = args["ratio"]
        ratio = values.parse_decimal(raw)
        return cls(inquiry=inquiry, surviving_name=surviving_name, baseline_name=baseline_name, ratio=ratio)


@dataclass(frozen=True)
class ConclusionClaim:
    """One admitted `Conclusion` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "Conclusion"

    conclusion: str
    inquiry: str
    conjecture: str
    conclusion_class: str
    statement: str
    evidence_digest: str
    published_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> ConclusionClaim:
        raw = args["conclusion"]
        conclusion = raw
        raw = args["inquiry"]
        inquiry = raw
        raw = args["conjecture"]
        conjecture = raw
        raw = args["conclusion_class"]
        conclusion_class = raw
        raw = args["statement"]
        statement = raw
        raw = args["evidence_digest"]
        evidence_digest = raw
        raw = args["published_at"]
        published_at = values.parse_timestamp(raw)
        return cls(conclusion=conclusion, inquiry=inquiry, conjecture=conjecture, conclusion_class=conclusion_class, statement=statement, evidence_digest=evidence_digest, published_at=published_at)


@dataclass(frozen=True)
class CurrentConclusionClaim:
    """One admitted `CurrentConclusion` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "CurrentConclusion"

    inquiry: str
    conclusion: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> CurrentConclusionClaim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["conclusion"]
        conclusion = raw
        return cls(inquiry=inquiry, conclusion=conclusion)


@dataclass(frozen=True)
class SupersedesConclusionClaim:
    """One admitted `SupersedesConclusion` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "SupersedesConclusion"

    successor_conclusion: str
    prior_conclusion: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> SupersedesConclusionClaim:
        raw = args["successor_conclusion"]
        successor_conclusion = raw
        raw = args["prior_conclusion"]
        prior_conclusion = raw
        return cls(successor_conclusion=successor_conclusion, prior_conclusion=prior_conclusion)


@dataclass(frozen=True)
class PublicationClaim:
    """One admitted `Publication` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "Publication"

    publication: str
    conclusion: str
    medium: str
    content_digest: str
    drafted_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> PublicationClaim:
        raw = args["publication"]
        publication = raw
        raw = args["conclusion"]
        conclusion = raw
        raw = args["medium"]
        medium = raw
        raw = args["content_digest"]
        content_digest = raw
        raw = args["drafted_at"]
        drafted_at = values.parse_timestamp(raw)
        return cls(publication=publication, conclusion=conclusion, medium=medium, content_digest=content_digest, drafted_at=drafted_at)


@dataclass(frozen=True)
class PublicationApprovedClaim:
    """One admitted `PublicationApproved` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "PublicationApproved"

    publication: str
    approved_at: datetime

    @classmethod
    def from_named(cls, args: dict[str, object]) -> PublicationApprovedClaim:
        raw = args["publication"]
        publication = raw
        raw = args["approved_at"]
        approved_at = values.parse_timestamp(raw)
        return cls(publication=publication, approved_at=approved_at)


@dataclass(frozen=True)
class LineageFromV1Claim:
    """One admitted `LineageFromV1` claim, decoded by declared kind."""

    PREDICATE: ClassVar[str] = "LineageFromV1"

    inquiry: str
    v1_investigation: str

    @classmethod
    def from_named(cls, args: dict[str, object]) -> LineageFromV1Claim:
        raw = args["inquiry"]
        inquiry = raw
        raw = args["v1_investigation"]
        v1_investigation = raw
        return cls(inquiry=inquiry, v1_investigation=v1_investigation)


@dataclass(frozen=True)
class InquiryOpenedPayload:
    """Payload of an emitted `InquiryOpened` intent."""

    INTENT: ClassVar[str] = "InquiryOpened"
    _ARG_ORDER: ClassVar[tuple] = ("inquiry",)

    inquiry: str

    @classmethod
    def from_args(cls, args: list[object]) -> InquiryOpenedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 1:
            raise ValueError(
                f"InquiryOpened: payload arity {len(args)} != contract arity 1 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class DataAcquisitionAuthorisedPayload:
    """Payload of an emitted `DataAcquisitionAuthorised` intent."""

    INTENT: ClassVar[str] = "DataAcquisitionAuthorised"
    _ARG_ORDER: ClassVar[tuple] = ("inquiry",)

    inquiry: str

    @classmethod
    def from_args(cls, args: list[object]) -> DataAcquisitionAuthorisedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 1:
            raise ValueError(
                f"DataAcquisitionAuthorised: payload arity {len(args)} != contract arity 1 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class AnalysisAuthorisedPayload:
    """Payload of an emitted `AnalysisAuthorised` intent."""

    INTENT: ClassVar[str] = "AnalysisAuthorised"
    _ARG_ORDER: ClassVar[tuple] = ("inquiry",)

    inquiry: str

    @classmethod
    def from_args(cls, args: list[object]) -> AnalysisAuthorisedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 1:
            raise ValueError(
                f"AnalysisAuthorised: payload arity {len(args)} != contract arity 1 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class ConjectureRegisteredPayload:
    """Payload of an emitted `ConjectureRegistered` intent."""

    INTENT: ClassVar[str] = "ConjectureRegistered"
    _ARG_ORDER: ClassVar[tuple] = ("conjecture",)

    conjecture: str

    @classmethod
    def from_args(cls, args: list[object]) -> ConjectureRegisteredPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 1:
            raise ValueError(
                f"ConjectureRegistered: payload arity {len(args)} != contract arity 1 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class ConclusionPublishedPayload:
    """Payload of an emitted `ConclusionPublished` intent."""

    INTENT: ClassVar[str] = "ConclusionPublished"
    _ARG_ORDER: ClassVar[tuple] = ("conclusion",)

    conclusion: str

    @classmethod
    def from_args(cls, args: list[object]) -> ConclusionPublishedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 1:
            raise ValueError(
                f"ConclusionPublished: payload arity {len(args)} != contract arity 1 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class ConclusionSupersededPayload:
    """Payload of an emitted `ConclusionSuperseded` intent."""

    INTENT: ClassVar[str] = "ConclusionSuperseded"
    _ARG_ORDER: ClassVar[tuple] = ("prior_conclusion", "successor_conclusion",)

    prior_conclusion: str
    successor_conclusion: str

    @classmethod
    def from_args(cls, args: list[object]) -> ConclusionSupersededPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 2:
            raise ValueError(
                f"ConclusionSuperseded: payload arity {len(args)} != contract arity 2 "
                f"(schema/payload skew)"
            )
        return cls(*args)


@dataclass(frozen=True)
class PublicationAuthorisedPayload:
    """Payload of an emitted `PublicationAuthorised` intent."""

    INTENT: ClassVar[str] = "PublicationAuthorised"
    _ARG_ORDER: ClassVar[tuple] = ("publication",)

    publication: str

    @classmethod
    def from_args(cls, args: list[object]) -> PublicationAuthorisedPayload:
        """Build from the decoded positional values of an outbox
        row's `arguments` (the adapter decodes; this names)."""
        if len(args) != 1:
            raise ValueError(
                f"PublicationAuthorised: payload arity {len(args)} != contract arity 1 "
                f"(schema/payload skew)"
            )
        return cls(*args)


INTENT_PAYLOADS = {
    "InquiryOpened": InquiryOpenedPayload,
    "DataAcquisitionAuthorised": DataAcquisitionAuthorisedPayload,
    "AnalysisAuthorised": AnalysisAuthorisedPayload,
    "ConjectureRegistered": ConjectureRegisteredPayload,
    "ConclusionPublished": ConclusionPublishedPayload,
    "ConclusionSuperseded": ConclusionSupersededPayload,
    "PublicationAuthorised": PublicationAuthorisedPayload,
}
